using System;
using System.Runtime.InteropServices;

namespace MegaLib.OS.Api;

using XrFlags64 = ulong;
using XrInstanceCreateFlags = ulong;
using XrSessionCreateFlags = ulong;
using XrViewStateFlags = ulong;
using XrVersion = ulong;
using XrInstance = IntPtr;
using XrSpace = IntPtr;
using XrSwapchain = IntPtr;
using XrSystemId = ulong;
using XrSession = IntPtr;
using XrBool32 = uint;
using XrTime = long;
using XrDuration = long;
using XrSwapchainCreateFlags = ulong;
using XrSpaceLocationFlags = ulong;
using XrPath = ulong;
using XrAction = IntPtr;
using XrActionSet = IntPtr;

//using XrSwapchainUsageFlags = System.UInt64;

public enum XrResult
{
  XR_SUCCESS = 0,
  XR_TIMEOUT_EXPIRED = 1,
  XR_SESSION_LOSS_PENDING = 3,
  XR_EVENT_UNAVAILABLE = 4,
  XR_SPACE_BOUNDS_UNAVAILABLE = 7,
  XR_SESSION_NOT_FOCUSED = 8,
  XR_FRAME_DISCARDED = 9,
  XR_ERROR_VALIDATION_FAILURE = -1,
  XR_ERROR_RUNTIME_FAILURE = -2,
  XR_ERROR_OUT_OF_MEMORY = -3,
  XR_ERROR_API_VERSION_UNSUPPORTED = -4,
  XR_ERROR_INITIALIZATION_FAILED = -6,
  XR_ERROR_FUNCTION_UNSUPPORTED = -7,
  XR_ERROR_FEATURE_UNSUPPORTED = -8,
  XR_ERROR_EXTENSION_NOT_PRESENT = -9,
  XR_ERROR_LIMIT_REACHED = -10,
  XR_ERROR_SIZE_INSUFFICIENT = -11,
  XR_ERROR_HANDLE_INVALID = -12,
  XR_ERROR_INSTANCE_LOST = -13,
  XR_ERROR_SESSION_RUNNING = -14,
  XR_ERROR_SESSION_NOT_RUNNING = -16,
  XR_ERROR_SESSION_LOST = -17,
  XR_ERROR_SYSTEM_INVALID = -18,
  XR_ERROR_PATH_INVALID = -19,
  XR_ERROR_PATH_COUNT_EXCEEDED = -20,
  XR_ERROR_PATH_FORMAT_INVALID = -21,
  XR_ERROR_PATH_UNSUPPORTED = -22,
  XR_ERROR_LAYER_INVALID = -23,
  XR_ERROR_LAYER_LIMIT_EXCEEDED = -24,
  XR_ERROR_SWAPCHAIN_RECT_INVALID = -25,
  XR_ERROR_SWAPCHAIN_FORMAT_UNSUPPORTED = -26,
  XR_ERROR_ACTION_TYPE_MISMATCH = -27,
  XR_ERROR_SESSION_NOT_READY = -28,
  XR_ERROR_SESSION_NOT_STOPPING = -29,
  XR_ERROR_TIME_INVALID = -30,
  XR_ERROR_REFERENCE_SPACE_UNSUPPORTED = -31,
  XR_ERROR_FILE_ACCESS_ERROR = -32,
  XR_ERROR_FILE_CONTENTS_INVALID = -33,
  XR_ERROR_FORM_FACTOR_UNSUPPORTED = -34,
  XR_ERROR_FORM_FACTOR_UNAVAILABLE = -35,
  XR_ERROR_API_LAYER_NOT_PRESENT = -36,
  XR_ERROR_CALL_ORDER_INVALID = -37,
  XR_ERROR_GRAPHICS_DEVICE_INVALID = -38,
  XR_ERROR_POSE_INVALID = -39,
  XR_ERROR_INDEX_OUT_OF_RANGE = -40,
  XR_ERROR_VIEW_CONFIGURATION_TYPE_UNSUPPORTED = -41,
  XR_ERROR_ENVIRONMENT_BLEND_MODE_UNSUPPORTED = -42,
  XR_ERROR_NAME_DUPLICATED = -44,
  XR_ERROR_NAME_INVALID = -45,
  XR_ERROR_ACTIONSET_NOT_ATTACHED = -46,
  XR_ERROR_ACTIONSETS_ALREADY_ATTACHED = -47,
  XR_ERROR_LOCALIZED_NAME_DUPLICATED = -48,
  XR_ERROR_LOCALIZED_NAME_INVALID = -49,
  XR_ERROR_GRAPHICS_REQUIREMENTS_CALL_MISSING = -50,
  XR_ERROR_RUNTIME_UNAVAILABLE = -51,
  XR_ERROR_ANDROID_THREAD_SETTINGS_ID_INVALID_KHR = -1000003000,
  XR_ERROR_ANDROID_THREAD_SETTINGS_FAILURE_KHR = -1000003001,
  XR_ERROR_CREATE_SPATIAL_ANCHOR_FAILED_MSFT = -1000039001,
  XR_ERROR_SECONDARY_VIEW_CONFIGURATION_TYPE_NOT_ENABLED_MSFT = -1000053000,
  XR_ERROR_CONTROLLER_MODEL_KEY_INVALID_MSFT = -1000055000,
  XR_ERROR_REPROJECTION_MODE_UNSUPPORTED_MSFT = -1000066000,
  XR_ERROR_COMPUTE_NEW_SCENE_NOT_COMPLETED_MSFT = -1000097000,
  XR_ERROR_SCENE_COMPONENT_ID_INVALID_MSFT = -1000097001,
  XR_ERROR_SCENE_COMPONENT_TYPE_MISMATCH_MSFT = -1000097002,
  XR_ERROR_SCENE_MESH_BUFFER_ID_INVALID_MSFT = -1000097003,
  XR_ERROR_SCENE_COMPUTE_FEATURE_INCOMPATIBLE_MSFT = -1000097004,
  XR_ERROR_SCENE_COMPUTE_CONSISTENCY_MISMATCH_MSFT = -1000097005,
  XR_ERROR_DISPLAY_REFRESH_RATE_UNSUPPORTED_FB = -1000101000,
  XR_ERROR_COLOR_SPACE_UNSUPPORTED_FB = -1000108000,
  XR_ERROR_SPACE_COMPONENT_NOT_SUPPORTED_FB = -1000113000,
  XR_ERROR_SPACE_COMPONENT_NOT_ENABLED_FB = -1000113001,
  XR_ERROR_SPACE_COMPONENT_STATUS_PENDING_FB = -1000113002,
  XR_ERROR_SPACE_COMPONENT_STATUS_ALREADY_SET_FB = -1000113003,
  XR_ERROR_UNEXPECTED_STATE_PASSTHROUGH_FB = -1000118000,
  XR_ERROR_FEATURE_ALREADY_CREATED_PASSTHROUGH_FB = -1000118001,
  XR_ERROR_FEATURE_REQUIRED_PASSTHROUGH_FB = -1000118002,
  XR_ERROR_NOT_PERMITTED_PASSTHROUGH_FB = -1000118003,
  XR_ERROR_INSUFFICIENT_RESOURCES_PASSTHROUGH_FB = -1000118004,
  XR_ERROR_UNKNOWN_PASSTHROUGH_FB = -1000118050,
  XR_ERROR_RENDER_MODEL_KEY_INVALID_FB = -1000119000,
  XR_RENDER_MODEL_UNAVAILABLE_FB = 1000119020,
  XR_ERROR_MARKER_NOT_TRACKED_VARJO = -1000124000,
  XR_ERROR_MARKER_ID_INVALID_VARJO = -1000124001,
  XR_ERROR_MARKER_DETECTOR_PERMISSION_DENIED_ML = -1000138000,
  XR_ERROR_MARKER_DETECTOR_LOCATE_FAILED_ML = -1000138001,
  XR_ERROR_MARKER_DETECTOR_INVALID_DATA_QUERY_ML = -1000138002,
  XR_ERROR_MARKER_DETECTOR_INVALID_CREATE_INFO_ML = -1000138003,
  XR_ERROR_MARKER_INVALID_ML = -1000138004,
  XR_ERROR_LOCALIZATION_MAP_INCOMPATIBLE_ML = -1000139000,
  XR_ERROR_LOCALIZATION_MAP_UNAVAILABLE_ML = -1000139001,
  XR_ERROR_LOCALIZATION_MAP_FAIL_ML = -1000139002,
  XR_ERROR_LOCALIZATION_MAP_IMPORT_EXPORT_PERMISSION_DENIED_ML = -1000139003,
  XR_ERROR_LOCALIZATION_MAP_PERMISSION_DENIED_ML = -1000139004,
  XR_ERROR_LOCALIZATION_MAP_ALREADY_EXISTS_ML = -1000139005,
  XR_ERROR_LOCALIZATION_MAP_CANNOT_EXPORT_CLOUD_MAP_ML = -1000139006,
  XR_ERROR_SPATIAL_ANCHOR_NAME_NOT_FOUND_MSFT = -1000142001,
  XR_ERROR_SPATIAL_ANCHOR_NAME_INVALID_MSFT = -1000142002,
  XR_SCENE_MARKER_DATA_NOT_STRING_MSFT = 1000147000,
  XR_ERROR_SPACE_MAPPING_INSUFFICIENT_FB = -1000169000,
  XR_ERROR_SPACE_LOCALIZATION_FAILED_FB = -1000169001,
  XR_ERROR_SPACE_NETWORK_TIMEOUT_FB = -1000169002,
  XR_ERROR_SPACE_NETWORK_REQUEST_FAILED_FB = -1000169003,
  XR_ERROR_SPACE_CLOUD_STORAGE_DISABLED_FB = -1000169004,
  XR_ERROR_PASSTHROUGH_COLOR_LUT_BUFFER_SIZE_MISMATCH_META = -1000266000,
  XR_ERROR_HINT_ALREADY_SET_QCOM = -1000306000,
  XR_ERROR_NOT_AN_ANCHOR_HTC = -1000319000,
  XR_ERROR_SPACE_NOT_LOCATABLE_EXT = -1000429000,
  XR_ERROR_PLANE_DETECTION_PERMISSION_DENIED_EXT = -1000429001,
  XR_RESULT_MAX_ENUM = 0x7FFFFFFF
}

public enum XrFormFactor
{
  XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY = 1,
  XR_FORM_FACTOR_HANDHELD_DISPLAY = 2,
  XR_FORM_FACTOR_MAX_ENUM = 0x7FFFFFFF
}

[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
public struct XrApplicationInfo
{
  [MarshalAs(UnmanagedType.ByValTStr, SizeConst = (int)OpenXR.XR_MAX_APPLICATION_NAME_SIZE)]
  public string ApplicationName;

  public uint ApplicationVersion;

  [MarshalAs(UnmanagedType.ByValTStr, SizeConst = (int)OpenXR.XR_MAX_ENGINE_NAME_SIZE)]
  public string EngineName;

  public uint EngineVersion;
  public XrVersion ApiVersion;
}

public enum XrStructureType
{
  XR_TYPE_UNKNOWN = 0,
  XR_TYPE_API_LAYER_PROPERTIES = 1,
  XR_TYPE_EXTENSION_PROPERTIES = 2,
  XR_TYPE_INSTANCE_CREATE_INFO = 3,
  XR_TYPE_SYSTEM_GET_INFO = 4,
  XR_TYPE_SYSTEM_PROPERTIES = 5,
  XR_TYPE_VIEW_LOCATE_INFO = 6,
  XR_TYPE_VIEW = 7,
  XR_TYPE_SESSION_CREATE_INFO = 8,
  XR_TYPE_SWAPCHAIN_CREATE_INFO = 9,
  XR_TYPE_SESSION_BEGIN_INFO = 10,
  XR_TYPE_VIEW_STATE = 11,
  XR_TYPE_FRAME_END_INFO = 12,
  XR_TYPE_HAPTIC_VIBRATION = 13,
  XR_TYPE_EVENT_DATA_BUFFER = 16,
  XR_TYPE_EVENT_DATA_INSTANCE_LOSS_PENDING = 17,
  XR_TYPE_EVENT_DATA_SESSION_STATE_CHANGED = 18,
  XR_TYPE_ACTION_STATE_BOOLEAN = 23,
  XR_TYPE_ACTION_STATE_FLOAT = 24,
  XR_TYPE_ACTION_STATE_VECTOR2F = 25,
  XR_TYPE_ACTION_STATE_POSE = 27,
  XR_TYPE_ACTION_SET_CREATE_INFO = 28,
  XR_TYPE_ACTION_CREATE_INFO = 29,
  XR_TYPE_INSTANCE_PROPERTIES = 32,
  XR_TYPE_FRAME_WAIT_INFO = 33,
  XR_TYPE_COMPOSITION_LAYER_PROJECTION = 35,
  XR_TYPE_COMPOSITION_LAYER_QUAD = 36,
  XR_TYPE_REFERENCE_SPACE_CREATE_INFO = 37,
  XR_TYPE_ACTION_SPACE_CREATE_INFO = 38,
  XR_TYPE_EVENT_DATA_REFERENCE_SPACE_CHANGE_PENDING = 40,
  XR_TYPE_VIEW_CONFIGURATION_VIEW = 41,
  XR_TYPE_SPACE_LOCATION = 42,
  XR_TYPE_SPACE_VELOCITY = 43,
  XR_TYPE_FRAME_STATE = 44,
  XR_TYPE_VIEW_CONFIGURATION_PROPERTIES = 45,
  XR_TYPE_FRAME_BEGIN_INFO = 46,
  XR_TYPE_COMPOSITION_LAYER_PROJECTION_VIEW = 48,
  XR_TYPE_EVENT_DATA_EVENTS_LOST = 49,
  XR_TYPE_INTERACTION_PROFILE_SUGGESTED_BINDING = 51,
  XR_TYPE_EVENT_DATA_INTERACTION_PROFILE_CHANGED = 52,
  XR_TYPE_INTERACTION_PROFILE_STATE = 53,
  XR_TYPE_SWAPCHAIN_IMAGE_ACQUIRE_INFO = 55,
  XR_TYPE_SWAPCHAIN_IMAGE_WAIT_INFO = 56,
  XR_TYPE_SWAPCHAIN_IMAGE_RELEASE_INFO = 57,
  XR_TYPE_ACTION_STATE_GET_INFO = 58,
  XR_TYPE_HAPTIC_ACTION_INFO = 59,
  XR_TYPE_SESSION_ACTION_SETS_ATTACH_INFO = 60,
  XR_TYPE_ACTIONS_SYNC_INFO = 61,
  XR_TYPE_BOUND_SOURCES_FOR_ACTION_ENUMERATE_INFO = 62,
  XR_TYPE_INPUT_SOURCE_LOCALIZED_NAME_GET_INFO = 63,

  // Provided by XR_KHR_composition_layer_cube
  XR_TYPE_COMPOSITION_LAYER_CUBE_KHR = 1000006000,

  // Provided by XR_KHR_android_create_instance
  XR_TYPE_INSTANCE_CREATE_INFO_ANDROID_KHR = 1000008000,

  // Provided by XR_KHR_composition_layer_depth
  XR_TYPE_COMPOSITION_LAYER_DEPTH_INFO_KHR = 1000010000,

  // Provided by XR_KHR_vulkan_swapchain_format_list
  XR_TYPE_VULKAN_SWAPCHAIN_FORMAT_LIST_CREATE_INFO_KHR = 1000014000,

  // Provided by XR_EXT_performance_settings
  XR_TYPE_EVENT_DATA_PERF_SETTINGS_EXT = 1000015000,

  // Provided by XR_KHR_composition_layer_cylinder
  XR_TYPE_COMPOSITION_LAYER_CYLINDER_KHR = 1000017000,

  // Provided by XR_KHR_composition_layer_equirect
  XR_TYPE_COMPOSITION_LAYER_EQUIRECT_KHR = 1000018000,

  // Provided by XR_EXT_debug_utils
  XR_TYPE_DEBUG_UTILS_OBJECT_NAME_INFO_EXT = 1000019000,

  // Provided by XR_EXT_debug_utils
  XR_TYPE_DEBUG_UTILS_MESSENGER_CALLBACK_DATA_EXT = 1000019001,

  // Provided by XR_EXT_debug_utils
  XR_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT = 1000019002,

  // Provided by XR_EXT_debug_utils
  XR_TYPE_DEBUG_UTILS_LABEL_EXT = 1000019003,

  // Provided by XR_KHR_opengl_enable
  XR_TYPE_GRAPHICS_BINDING_OPENGL_WIN32_KHR = 1000023000,

  // Provided by XR_KHR_opengl_enable
  XR_TYPE_GRAPHICS_BINDING_OPENGL_XLIB_KHR = 1000023001,

  // Provided by XR_KHR_opengl_enable
  XR_TYPE_GRAPHICS_BINDING_OPENGL_XCB_KHR = 1000023002,

  // Provided by XR_KHR_opengl_enable
  XR_TYPE_GRAPHICS_BINDING_OPENGL_WAYLAND_KHR = 1000023003,

  // Provided by XR_KHR_opengl_enable
  XR_TYPE_SWAPCHAIN_IMAGE_OPENGL_KHR = 1000023004,

  // Provided by XR_KHR_opengl_enable
  XR_TYPE_GRAPHICS_REQUIREMENTS_OPENGL_KHR = 1000023005,

  // Provided by XR_KHR_opengl_es_enable
  XR_TYPE_GRAPHICS_BINDING_OPENGL_ES_ANDROID_KHR = 1000024001,

  // Provided by XR_KHR_opengl_es_enable
  XR_TYPE_SWAPCHAIN_IMAGE_OPENGL_ES_KHR = 1000024002,

  // Provided by XR_KHR_opengl_es_enable
  XR_TYPE_GRAPHICS_REQUIREMENTS_OPENGL_ES_KHR = 1000024003,

  // Provided by XR_KHR_vulkan_enable
  XR_TYPE_GRAPHICS_BINDING_VULKAN_KHR = 1000025000,

  // Provided by XR_KHR_vulkan_enable
  XR_TYPE_SWAPCHAIN_IMAGE_VULKAN_KHR = 1000025001,

  // Provided by XR_KHR_vulkan_enable
  XR_TYPE_GRAPHICS_REQUIREMENTS_VULKAN_KHR = 1000025002,

  // Provided by XR_KHR_D3D11_enable
  XR_TYPE_GRAPHICS_BINDING_D3D11_KHR = 1000027000,

  // Provided by XR_KHR_D3D11_enable
  XR_TYPE_SWAPCHAIN_IMAGE_D3D11_KHR = 1000027001,

  // Provided by XR_KHR_D3D11_enable
  XR_TYPE_GRAPHICS_REQUIREMENTS_D3D11_KHR = 1000027002,

  // Provided by XR_KHR_D3D12_enable
  XR_TYPE_GRAPHICS_BINDING_D3D12_KHR = 1000028000,

  // Provided by XR_KHR_D3D12_enable
  XR_TYPE_SWAPCHAIN_IMAGE_D3D12_KHR = 1000028001,

  // Provided by XR_KHR_D3D12_enable
  XR_TYPE_GRAPHICS_REQUIREMENTS_D3D12_KHR = 1000028002,

  // Provided by XR_EXT_eye_gaze_interaction
  XR_TYPE_SYSTEM_EYE_GAZE_INTERACTION_PROPERTIES_EXT = 1000030000,

  // Provided by XR_EXT_eye_gaze_interaction
  XR_TYPE_EYE_GAZE_SAMPLE_TIME_EXT = 1000030001,

  // Provided by XR_KHR_visibility_mask
  XR_TYPE_VISIBILITY_MASK_KHR = 1000031000,

  // Provided by XR_KHR_visibility_mask
  XR_TYPE_EVENT_DATA_VISIBILITY_MASK_CHANGED_KHR = 1000031001,

  // Provided by XR_EXTX_overlay
  XR_TYPE_SESSION_CREATE_INFO_OVERLAY_EXTX = 1000033000,

  // Provided by XR_EXTX_overlay
  XR_TYPE_EVENT_DATA_MAIN_SESSION_VISIBILITY_CHANGED_EXTX = 1000033003,

  // Provided by XR_KHR_composition_layer_color_scale_bias
  XR_TYPE_COMPOSITION_LAYER_COLOR_SCALE_BIAS_KHR = 1000034000,

  // Provided by XR_MSFT_spatial_anchor
  XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_MSFT = 1000039000,

  // Provided by XR_MSFT_spatial_anchor
  XR_TYPE_SPATIAL_ANCHOR_SPACE_CREATE_INFO_MSFT = 1000039001,

  // Provided by XR_FB_composition_layer_image_layout
  XR_TYPE_COMPOSITION_LAYER_IMAGE_LAYOUT_FB = 1000040000,

  // Provided by XR_FB_composition_layer_alpha_blend
  XR_TYPE_COMPOSITION_LAYER_ALPHA_BLEND_FB = 1000041001,

  // Provided by XR_EXT_view_configuration_depth_range
  XR_TYPE_VIEW_CONFIGURATION_DEPTH_RANGE_EXT = 1000046000,

  // Provided by XR_MNDX_egl_enable
  XR_TYPE_GRAPHICS_BINDING_EGL_MNDX = 1000048004,

  // Provided by XR_MSFT_spatial_graph_bridge
  XR_TYPE_SPATIAL_GRAPH_NODE_SPACE_CREATE_INFO_MSFT = 1000049000,

  // Provided by XR_MSFT_spatial_graph_bridge
  XR_TYPE_SPATIAL_GRAPH_STATIC_NODE_BINDING_CREATE_INFO_MSFT = 1000049001,

  // Provided by XR_MSFT_spatial_graph_bridge
  XR_TYPE_SPATIAL_GRAPH_NODE_BINDING_PROPERTIES_GET_INFO_MSFT = 1000049002,

  // Provided by XR_MSFT_spatial_graph_bridge
  XR_TYPE_SPATIAL_GRAPH_NODE_BINDING_PROPERTIES_MSFT = 1000049003,

  // Provided by XR_EXT_hand_tracking
  XR_TYPE_SYSTEM_HAND_TRACKING_PROPERTIES_EXT = 1000051000,

  // Provided by XR_EXT_hand_tracking
  XR_TYPE_HAND_TRACKER_CREATE_INFO_EXT = 1000051001,

  // Provided by XR_EXT_hand_tracking
  XR_TYPE_HAND_JOINTS_LOCATE_INFO_EXT = 1000051002,

  // Provided by XR_EXT_hand_tracking
  XR_TYPE_HAND_JOINT_LOCATIONS_EXT = 1000051003,

  // Provided by XR_EXT_hand_tracking
  XR_TYPE_HAND_JOINT_VELOCITIES_EXT = 1000051004,

  // Provided by XR_MSFT_hand_tracking_mesh
  XR_TYPE_SYSTEM_HAND_TRACKING_MESH_PROPERTIES_MSFT = 1000052000,

  // Provided by XR_MSFT_hand_tracking_mesh
  XR_TYPE_HAND_MESH_SPACE_CREATE_INFO_MSFT = 1000052001,

  // Provided by XR_MSFT_hand_tracking_mesh
  XR_TYPE_HAND_MESH_UPDATE_INFO_MSFT = 1000052002,

  // Provided by XR_MSFT_hand_tracking_mesh
  XR_TYPE_HAND_MESH_MSFT = 1000052003,

  // Provided by XR_MSFT_hand_tracking_mesh
  XR_TYPE_HAND_POSE_TYPE_INFO_MSFT = 1000052004,

  // Provided by XR_MSFT_secondary_view_configuration
  XR_TYPE_SECONDARY_VIEW_CONFIGURATION_SESSION_BEGIN_INFO_MSFT = 1000053000,

  // Provided by XR_MSFT_secondary_view_configuration
  XR_TYPE_SECONDARY_VIEW_CONFIGURATION_STATE_MSFT = 1000053001,

  // Provided by XR_MSFT_secondary_view_configuration
  XR_TYPE_SECONDARY_VIEW_CONFIGURATION_FRAME_STATE_MSFT = 1000053002,

  // Provided by XR_MSFT_secondary_view_configuration
  XR_TYPE_SECONDARY_VIEW_CONFIGURATION_FRAME_END_INFO_MSFT = 1000053003,

  // Provided by XR_MSFT_secondary_view_configuration
  XR_TYPE_SECONDARY_VIEW_CONFIGURATION_LAYER_INFO_MSFT = 1000053004,

  // Provided by XR_MSFT_secondary_view_configuration
  XR_TYPE_SECONDARY_VIEW_CONFIGURATION_SWAPCHAIN_CREATE_INFO_MSFT = 1000053005,

  // Provided by XR_MSFT_controller_model
  XR_TYPE_CONTROLLER_MODEL_KEY_STATE_MSFT = 1000055000,

  // Provided by XR_MSFT_controller_model
  XR_TYPE_CONTROLLER_MODEL_NODE_PROPERTIES_MSFT = 1000055001,

  // Provided by XR_MSFT_controller_model
  XR_TYPE_CONTROLLER_MODEL_PROPERTIES_MSFT = 1000055002,

  // Provided by XR_MSFT_controller_model
  XR_TYPE_CONTROLLER_MODEL_NODE_STATE_MSFT = 1000055003,

  // Provided by XR_MSFT_controller_model
  XR_TYPE_CONTROLLER_MODEL_STATE_MSFT = 1000055004,

  // Provided by XR_EPIC_view_configuration_fov
  XR_TYPE_VIEW_CONFIGURATION_VIEW_FOV_EPIC = 1000059000,

  // Provided by XR_MSFT_holographic_window_attachment
  XR_TYPE_HOLOGRAPHIC_WINDOW_ATTACHMENT_MSFT = 1000063000,

  // Provided by XR_MSFT_composition_layer_reprojection
  XR_TYPE_COMPOSITION_LAYER_REPROJECTION_INFO_MSFT = 1000066000,

  // Provided by XR_MSFT_composition_layer_reprojection
  XR_TYPE_COMPOSITION_LAYER_REPROJECTION_PLANE_OVERRIDE_MSFT = 1000066001,

  // Provided by XR_FB_android_surface_swapchain_create
  XR_TYPE_ANDROID_SURFACE_SWAPCHAIN_CREATE_INFO_FB = 1000070000,

  // Provided by XR_FB_composition_layer_secure_content
  XR_TYPE_COMPOSITION_LAYER_SECURE_CONTENT_FB = 1000072000,

  // Provided by XR_FB_body_tracking
  XR_TYPE_BODY_TRACKER_CREATE_INFO_FB = 1000076001,

  // Provided by XR_FB_body_tracking
  XR_TYPE_BODY_JOINTS_LOCATE_INFO_FB = 1000076002,

  // Provided by XR_FB_body_tracking
  XR_TYPE_SYSTEM_BODY_TRACKING_PROPERTIES_FB = 1000076004,

  // Provided by XR_FB_body_tracking
  XR_TYPE_BODY_JOINT_LOCATIONS_FB = 1000076005,

  // Provided by XR_FB_body_tracking
  XR_TYPE_BODY_SKELETON_FB = 1000076006,

  // Provided by XR_EXT_dpad_binding
  XR_TYPE_INTERACTION_PROFILE_DPAD_BINDING_EXT = 1000078000,

  // Provided by XR_VALVE_analog_threshold
  XR_TYPE_INTERACTION_PROFILE_ANALOG_THRESHOLD_VALVE = 1000079000,

  // Provided by XR_EXT_hand_joints_motion_range
  XR_TYPE_HAND_JOINTS_MOTION_RANGE_INFO_EXT = 1000080000,

  // Provided by XR_KHR_loader_init_android
  XR_TYPE_LOADER_INIT_INFO_ANDROID_KHR = 1000089000,

  // Provided by XR_KHR_vulkan_enable2
  XR_TYPE_VULKAN_INSTANCE_CREATE_INFO_KHR = 1000090000,

  // Provided by XR_KHR_vulkan_enable2
  XR_TYPE_VULKAN_DEVICE_CREATE_INFO_KHR = 1000090001,

  // Provided by XR_KHR_vulkan_enable2
  XR_TYPE_VULKAN_GRAPHICS_DEVICE_GET_INFO_KHR = 1000090003,

  // Provided by XR_KHR_composition_layer_equirect2
  XR_TYPE_COMPOSITION_LAYER_EQUIRECT2_KHR = 1000091000,

  // Provided by XR_MSFT_scene_understanding
  XR_TYPE_SCENE_OBSERVER_CREATE_INFO_MSFT = 1000097000,

  // Provided by XR_MSFT_scene_understanding
  XR_TYPE_SCENE_CREATE_INFO_MSFT = 1000097001,

  // Provided by XR_MSFT_scene_understanding
  XR_TYPE_NEW_SCENE_COMPUTE_INFO_MSFT = 1000097002,

  // Provided by XR_MSFT_scene_understanding
  XR_TYPE_VISUAL_MESH_COMPUTE_LOD_INFO_MSFT = 1000097003,

  // Provided by XR_MSFT_scene_understanding
  XR_TYPE_SCENE_COMPONENTS_MSFT = 1000097004,

  // Provided by XR_MSFT_scene_understanding
  XR_TYPE_SCENE_COMPONENTS_GET_INFO_MSFT = 1000097005,

  // Provided by XR_MSFT_scene_understanding
  XR_TYPE_SCENE_COMPONENT_LOCATIONS_MSFT = 1000097006,

  // Provided by XR_MSFT_scene_understanding
  XR_TYPE_SCENE_COMPONENTS_LOCATE_INFO_MSFT = 1000097007,

  // Provided by XR_MSFT_scene_understanding
  XR_TYPE_SCENE_OBJECTS_MSFT = 1000097008,

  // Provided by XR_MSFT_scene_understanding
  XR_TYPE_SCENE_COMPONENT_PARENT_FILTER_INFO_MSFT = 1000097009,

  // Provided by XR_MSFT_scene_understanding
  XR_TYPE_SCENE_OBJECT_TYPES_FILTER_INFO_MSFT = 1000097010,

  // Provided by XR_MSFT_scene_understanding
  XR_TYPE_SCENE_PLANES_MSFT = 1000097011,

  // Provided by XR_MSFT_scene_understanding
  XR_TYPE_SCENE_PLANE_ALIGNMENT_FILTER_INFO_MSFT = 1000097012,

  // Provided by XR_MSFT_scene_understanding
  XR_TYPE_SCENE_MESHES_MSFT = 1000097013,

  // Provided by XR_MSFT_scene_understanding
  XR_TYPE_SCENE_MESH_BUFFERS_GET_INFO_MSFT = 1000097014,

  // Provided by XR_MSFT_scene_understanding
  XR_TYPE_SCENE_MESH_BUFFERS_MSFT = 1000097015,

  // Provided by XR_MSFT_scene_understanding
  XR_TYPE_SCENE_MESH_VERTEX_BUFFER_MSFT = 1000097016,

  // Provided by XR_MSFT_scene_understanding
  XR_TYPE_SCENE_MESH_INDICES_UINT32_MSFT = 1000097017,

  // Provided by XR_MSFT_scene_understanding
  XR_TYPE_SCENE_MESH_INDICES_UINT16_MSFT = 1000097018,

  // Provided by XR_MSFT_scene_understanding_serialization
  XR_TYPE_SERIALIZED_SCENE_FRAGMENT_DATA_GET_INFO_MSFT = 1000098000,

  // Provided by XR_MSFT_scene_understanding_serialization
  XR_TYPE_SCENE_DESERIALIZE_INFO_MSFT = 1000098001,

  // Provided by XR_FB_display_refresh_rate
  XR_TYPE_EVENT_DATA_DISPLAY_REFRESH_RATE_CHANGED_FB = 1000101000,

  // Provided by XR_HTCX_vive_tracker_interaction
  XR_TYPE_VIVE_TRACKER_PATHS_HTCX = 1000103000,

  // Provided by XR_HTCX_vive_tracker_interaction
  XR_TYPE_EVENT_DATA_VIVE_TRACKER_CONNECTED_HTCX = 1000103001,

  // Provided by XR_HTC_facial_tracking
  XR_TYPE_SYSTEM_FACIAL_TRACKING_PROPERTIES_HTC = 1000104000,

  // Provided by XR_HTC_facial_tracking
  XR_TYPE_FACIAL_TRACKER_CREATE_INFO_HTC = 1000104001,

  // Provided by XR_HTC_facial_tracking
  XR_TYPE_FACIAL_EXPRESSIONS_HTC = 1000104002,

  // Provided by XR_FB_color_space
  XR_TYPE_SYSTEM_COLOR_SPACE_PROPERTIES_FB = 1000108000,

  // Provided by XR_FB_hand_tracking_mesh
  XR_TYPE_HAND_TRACKING_MESH_FB = 1000110001,

  // Provided by XR_FB_hand_tracking_mesh
  XR_TYPE_HAND_TRACKING_SCALE_FB = 1000110003,

  // Provided by XR_FB_hand_tracking_aim
  XR_TYPE_HAND_TRACKING_AIM_STATE_FB = 1000111001,

  // Provided by XR_FB_hand_tracking_capsules
  XR_TYPE_HAND_TRACKING_CAPSULES_STATE_FB = 1000112000,

  // Provided by XR_FB_spatial_entity
  XR_TYPE_SYSTEM_SPATIAL_ENTITY_PROPERTIES_FB = 1000113004,

  // Provided by XR_FB_spatial_entity
  XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_FB = 1000113003,

  // Provided by XR_FB_spatial_entity
  XR_TYPE_SPACE_COMPONENT_STATUS_SET_INFO_FB = 1000113007,

  // Provided by XR_FB_spatial_entity
  XR_TYPE_SPACE_COMPONENT_STATUS_FB = 1000113001,

  // Provided by XR_FB_spatial_entity
  XR_TYPE_EVENT_DATA_SPATIAL_ANCHOR_CREATE_COMPLETE_FB = 1000113005,

  // Provided by XR_FB_spatial_entity
  XR_TYPE_EVENT_DATA_SPACE_SET_STATUS_COMPLETE_FB = 1000113006,

  // Provided by XR_FB_foveation
  XR_TYPE_FOVEATION_PROFILE_CREATE_INFO_FB = 1000114000,

  // Provided by XR_FB_foveation
  XR_TYPE_SWAPCHAIN_CREATE_INFO_FOVEATION_FB = 1000114001,

  // Provided by XR_FB_foveation
  XR_TYPE_SWAPCHAIN_STATE_FOVEATION_FB = 1000114002,

  // Provided by XR_FB_foveation_configuration
  XR_TYPE_FOVEATION_LEVEL_PROFILE_CREATE_INFO_FB = 1000115000,

  // Provided by XR_FB_keyboard_tracking
  XR_TYPE_KEYBOARD_SPACE_CREATE_INFO_FB = 1000116009,

  // Provided by XR_FB_keyboard_tracking
  XR_TYPE_KEYBOARD_TRACKING_QUERY_FB = 1000116004,

  // Provided by XR_FB_keyboard_tracking
  XR_TYPE_SYSTEM_KEYBOARD_TRACKING_PROPERTIES_FB = 1000116002,

  // Provided by XR_FB_triangle_mesh
  XR_TYPE_TRIANGLE_MESH_CREATE_INFO_FB = 1000117001,

  // Provided by XR_FB_passthrough
  XR_TYPE_SYSTEM_PASSTHROUGH_PROPERTIES_FB = 1000118000,

  // Provided by XR_FB_passthrough
  XR_TYPE_PASSTHROUGH_CREATE_INFO_FB = 1000118001,

  // Provided by XR_FB_passthrough
  XR_TYPE_PASSTHROUGH_LAYER_CREATE_INFO_FB = 1000118002,

  // Provided by XR_FB_passthrough
  XR_TYPE_COMPOSITION_LAYER_PASSTHROUGH_FB = 1000118003,

  // Provided by XR_FB_passthrough
  XR_TYPE_GEOMETRY_INSTANCE_CREATE_INFO_FB = 1000118004,

  // Provided by XR_FB_passthrough
  XR_TYPE_GEOMETRY_INSTANCE_TRANSFORM_FB = 1000118005,

  // Provided by XR_FB_passthrough
  XR_TYPE_SYSTEM_PASSTHROUGH_PROPERTIES2_FB = 1000118006,

  // Provided by XR_FB_passthrough
  XR_TYPE_PASSTHROUGH_STYLE_FB = 1000118020,

  // Provided by XR_FB_passthrough
  XR_TYPE_PASSTHROUGH_COLOR_MAP_MONO_TO_RGBA_FB = 1000118021,

  // Provided by XR_FB_passthrough
  XR_TYPE_PASSTHROUGH_COLOR_MAP_MONO_TO_MONO_FB = 1000118022,

  // Provided by XR_FB_passthrough
  XR_TYPE_PASSTHROUGH_BRIGHTNESS_CONTRAST_SATURATION_FB = 1000118023,

  // Provided by XR_FB_passthrough
  XR_TYPE_EVENT_DATA_PASSTHROUGH_STATE_CHANGED_FB = 1000118030,

  // Provided by XR_FB_render_model
  XR_TYPE_RENDER_MODEL_PATH_INFO_FB = 1000119000,

  // Provided by XR_FB_render_model
  XR_TYPE_RENDER_MODEL_PROPERTIES_FB = 1000119001,

  // Provided by XR_FB_render_model
  XR_TYPE_RENDER_MODEL_BUFFER_FB = 1000119002,

  // Provided by XR_FB_render_model
  XR_TYPE_RENDER_MODEL_LOAD_INFO_FB = 1000119003,

  // Provided by XR_FB_render_model
  XR_TYPE_SYSTEM_RENDER_MODEL_PROPERTIES_FB = 1000119004,

  // Provided by XR_FB_render_model
  XR_TYPE_RENDER_MODEL_CAPABILITIES_REQUEST_FB = 1000119005,

  // Provided by XR_KHR_binding_modification
  XR_TYPE_BINDING_MODIFICATIONS_KHR = 1000120000,

  // Provided by XR_VARJO_foveated_rendering
  XR_TYPE_VIEW_LOCATE_FOVEATED_RENDERING_VARJO = 1000121000,

  // Provided by XR_VARJO_foveated_rendering
  XR_TYPE_FOVEATED_VIEW_CONFIGURATION_VIEW_VARJO = 1000121001,

  // Provided by XR_VARJO_foveated_rendering
  XR_TYPE_SYSTEM_FOVEATED_RENDERING_PROPERTIES_VARJO = 1000121002,

  // Provided by XR_VARJO_composition_layer_depth_test
  XR_TYPE_COMPOSITION_LAYER_DEPTH_TEST_VARJO = 1000122000,

  // Provided by XR_VARJO_marker_tracking
  XR_TYPE_SYSTEM_MARKER_TRACKING_PROPERTIES_VARJO = 1000124000,

  // Provided by XR_VARJO_marker_tracking
  XR_TYPE_EVENT_DATA_MARKER_TRACKING_UPDATE_VARJO = 1000124001,

  // Provided by XR_VARJO_marker_tracking
  XR_TYPE_MARKER_SPACE_CREATE_INFO_VARJO = 1000124002,

  // Provided by XR_ML_frame_end_info
  XR_TYPE_FRAME_END_INFO_ML = 1000135000,

  // Provided by XR_ML_global_dimmer
  XR_TYPE_GLOBAL_DIMMER_FRAME_END_INFO_ML = 1000136000,

  // Provided by XR_ML_compat
  XR_TYPE_COORDINATE_SPACE_CREATE_INFO_ML = 1000137000,

  // Provided by XR_ML_marker_understanding
  XR_TYPE_SYSTEM_MARKER_UNDERSTANDING_PROPERTIES_ML = 1000138000,

  // Provided by XR_ML_marker_understanding
  XR_TYPE_MARKER_DETECTOR_CREATE_INFO_ML = 1000138001,

  // Provided by XR_ML_marker_understanding
  XR_TYPE_MARKER_DETECTOR_ARUCO_INFO_ML = 1000138002,

  // Provided by XR_ML_marker_understanding
  XR_TYPE_MARKER_DETECTOR_SIZE_INFO_ML = 1000138003,

  // Provided by XR_ML_marker_understanding
  XR_TYPE_MARKER_DETECTOR_APRIL_TAG_INFO_ML = 1000138004,

  // Provided by XR_ML_marker_understanding
  XR_TYPE_MARKER_DETECTOR_CUSTOM_PROFILE_INFO_ML = 1000138005,

  // Provided by XR_ML_marker_understanding
  XR_TYPE_MARKER_DETECTOR_SNAPSHOT_INFO_ML = 1000138006,

  // Provided by XR_ML_marker_understanding
  XR_TYPE_MARKER_DETECTOR_STATE_ML = 1000138007,

  // Provided by XR_ML_marker_understanding
  XR_TYPE_MARKER_SPACE_CREATE_INFO_ML = 1000138008,

  // Provided by XR_ML_localization_map
  XR_TYPE_LOCALIZATION_MAP_ML = 1000139000,

  // Provided by XR_ML_localization_map
  XR_TYPE_EVENT_DATA_LOCALIZATION_CHANGED_ML = 1000139001,

  // Provided by XR_ML_localization_map
  XR_TYPE_MAP_LOCALIZATION_REQUEST_INFO_ML = 1000139002,

  // Provided by XR_ML_localization_map
  XR_TYPE_LOCALIZATION_MAP_IMPORT_INFO_ML = 1000139003,

  // Provided by XR_ML_localization_map
  XR_TYPE_LOCALIZATION_ENABLE_EVENTS_INFO_ML = 1000139004,

  // Provided by XR_ML_user_calibration
  XR_TYPE_EVENT_DATA_HEADSET_FIT_CHANGED_ML = 1000472000,

  // Provided by XR_ML_user_calibration
  XR_TYPE_EVENT_DATA_EYE_CALIBRATION_CHANGED_ML = 1000472001,

  // Provided by XR_ML_user_calibration
  XR_TYPE_USER_CALIBRATION_ENABLE_EVENTS_INFO_ML = 1000472002,

  // Provided by XR_MSFT_spatial_anchor_persistence
  XR_TYPE_SPATIAL_ANCHOR_PERSISTENCE_INFO_MSFT = 1000142000,

  // Provided by XR_MSFT_spatial_anchor_persistence
  XR_TYPE_SPATIAL_ANCHOR_FROM_PERSISTED_ANCHOR_CREATE_INFO_MSFT = 1000142001,

  // Provided by XR_MSFT_scene_marker
  XR_TYPE_SCENE_MARKERS_MSFT = 1000147000,

  // Provided by XR_MSFT_scene_marker
  XR_TYPE_SCENE_MARKER_TYPE_FILTER_MSFT = 1000147001,

  // Provided by XR_MSFT_scene_marker
  XR_TYPE_SCENE_MARKER_QR_CODES_MSFT = 1000147002,

  // Provided by XR_FB_spatial_entity_query
  XR_TYPE_SPACE_QUERY_INFO_FB = 1000156001,

  // Provided by XR_FB_spatial_entity_query
  XR_TYPE_SPACE_QUERY_RESULTS_FB = 1000156002,

  // Provided by XR_FB_spatial_entity_query
  XR_TYPE_SPACE_STORAGE_LOCATION_FILTER_INFO_FB = 1000156003,

  // Provided by XR_FB_spatial_entity_query
  XR_TYPE_SPACE_UUID_FILTER_INFO_FB = 1000156054,

  // Provided by XR_FB_spatial_entity_query
  XR_TYPE_SPACE_COMPONENT_FILTER_INFO_FB = 1000156052,

  // Provided by XR_FB_spatial_entity_query
  XR_TYPE_EVENT_DATA_SPACE_QUERY_RESULTS_AVAILABLE_FB = 1000156103,

  // Provided by XR_FB_spatial_entity_query
  XR_TYPE_EVENT_DATA_SPACE_QUERY_COMPLETE_FB = 1000156104,

  // Provided by XR_FB_spatial_entity_storage
  XR_TYPE_SPACE_SAVE_INFO_FB = 1000158000,

  // Provided by XR_FB_spatial_entity_storage
  XR_TYPE_SPACE_ERASE_INFO_FB = 1000158001,

  // Provided by XR_FB_spatial_entity_storage
  XR_TYPE_EVENT_DATA_SPACE_SAVE_COMPLETE_FB = 1000158106,

  // Provided by XR_FB_spatial_entity_storage
  XR_TYPE_EVENT_DATA_SPACE_ERASE_COMPLETE_FB = 1000158107,

  // Provided by XR_FB_foveation_vulkan
  XR_TYPE_SWAPCHAIN_IMAGE_FOVEATION_VULKAN_FB = 1000160000,

  // Provided by XR_FB_swapchain_update_state_android_surface
  XR_TYPE_SWAPCHAIN_STATE_ANDROID_SURFACE_DIMENSIONS_FB = 1000161000,

  // Provided by XR_FB_swapchain_update_state_opengl_es
  XR_TYPE_SWAPCHAIN_STATE_SAMPLER_OPENGL_ES_FB = 1000162000,

  // Provided by XR_FB_swapchain_update_state_vulkan
  XR_TYPE_SWAPCHAIN_STATE_SAMPLER_VULKAN_FB = 1000163000,

  // Provided by XR_FB_spatial_entity_sharing
  XR_TYPE_SPACE_SHARE_INFO_FB = 1000169001,

  // Provided by XR_FB_spatial_entity_sharing
  XR_TYPE_EVENT_DATA_SPACE_SHARE_COMPLETE_FB = 1000169002,

  // Provided by XR_FB_space_warp
  XR_TYPE_COMPOSITION_LAYER_SPACE_WARP_INFO_FB = 1000171000,

  // Provided by XR_FB_space_warp
  XR_TYPE_SYSTEM_SPACE_WARP_PROPERTIES_FB = 1000171001,

  // Provided by XR_FB_haptic_amplitude_envelope
  XR_TYPE_HAPTIC_AMPLITUDE_ENVELOPE_VIBRATION_FB = 1000173001,

  // Provided by XR_FB_scene
  XR_TYPE_SEMANTIC_LABELS_FB = 1000175000,

  // Provided by XR_FB_scene
  XR_TYPE_ROOM_LAYOUT_FB = 1000175001,

  // Provided by XR_FB_scene
  XR_TYPE_BOUNDARY_2D_FB = 1000175002,

  // Provided by XR_FB_scene
  XR_TYPE_SEMANTIC_LABELS_SUPPORT_INFO_FB = 1000175010,

  // Provided by XR_ALMALENCE_digital_lens_control
  XR_TYPE_DIGITAL_LENS_CONTROL_ALMALENCE = 1000196000,

  // Provided by XR_FB_scene_capture
  XR_TYPE_EVENT_DATA_SCENE_CAPTURE_COMPLETE_FB = 1000198001,

  // Provided by XR_FB_scene_capture
  XR_TYPE_SCENE_CAPTURE_REQUEST_INFO_FB = 1000198050,

  // Provided by XR_FB_spatial_entity_container
  XR_TYPE_SPACE_CONTAINER_FB = 1000199000,

  // Provided by XR_META_foveation_eye_tracked
  XR_TYPE_FOVEATION_EYE_TRACKED_PROFILE_CREATE_INFO_META = 1000200000,

  // Provided by XR_META_foveation_eye_tracked
  XR_TYPE_FOVEATION_EYE_TRACKED_STATE_META = 1000200001,

  // Provided by XR_META_foveation_eye_tracked
  XR_TYPE_SYSTEM_FOVEATION_EYE_TRACKED_PROPERTIES_META = 1000200002,

  // Provided by XR_FB_face_tracking
  XR_TYPE_SYSTEM_FACE_TRACKING_PROPERTIES_FB = 1000201004,

  // Provided by XR_FB_face_tracking
  XR_TYPE_FACE_TRACKER_CREATE_INFO_FB = 1000201005,

  // Provided by XR_FB_face_tracking
  XR_TYPE_FACE_EXPRESSION_INFO_FB = 1000201002,

  // Provided by XR_FB_face_tracking
  XR_TYPE_FACE_EXPRESSION_WEIGHTS_FB = 1000201006,

  // Provided by XR_FB_eye_tracking_social
  XR_TYPE_EYE_TRACKER_CREATE_INFO_FB = 1000202001,

  // Provided by XR_FB_eye_tracking_social
  XR_TYPE_EYE_GAZES_INFO_FB = 1000202002,

  // Provided by XR_FB_eye_tracking_social
  XR_TYPE_EYE_GAZES_FB = 1000202003,

  // Provided by XR_FB_eye_tracking_social
  XR_TYPE_SYSTEM_EYE_TRACKING_PROPERTIES_FB = 1000202004,

  // Provided by XR_FB_passthrough_keyboard_hands
  XR_TYPE_PASSTHROUGH_KEYBOARD_HANDS_INTENSITY_FB = 1000203002,

  // Provided by XR_FB_composition_layer_settings
  XR_TYPE_COMPOSITION_LAYER_SETTINGS_FB = 1000204000,

  // Provided by XR_FB_haptic_pcm
  XR_TYPE_HAPTIC_PCM_VIBRATION_FB = 1000209001,

  // Provided by XR_FB_haptic_pcm
  XR_TYPE_DEVICE_PCM_SAMPLE_RATE_STATE_FB = 1000209002,

  // Provided by XR_FB_composition_layer_depth_test
  XR_TYPE_COMPOSITION_LAYER_DEPTH_TEST_FB = 1000212000,

  // Provided by XR_META_local_dimming
  XR_TYPE_LOCAL_DIMMING_FRAME_END_INFO_META = 1000216000,

  // Provided by XR_META_passthrough_preferences
  XR_TYPE_PASSTHROUGH_PREFERENCES_META = 1000217000,

  // Provided by XR_META_virtual_keyboard
  XR_TYPE_SYSTEM_VIRTUAL_KEYBOARD_PROPERTIES_META = 1000219001,

  // Provided by XR_META_virtual_keyboard
  XR_TYPE_VIRTUAL_KEYBOARD_CREATE_INFO_META = 1000219002,

  // Provided by XR_META_virtual_keyboard
  XR_TYPE_VIRTUAL_KEYBOARD_SPACE_CREATE_INFO_META = 1000219003,

  // Provided by XR_META_virtual_keyboard
  XR_TYPE_VIRTUAL_KEYBOARD_LOCATION_INFO_META = 1000219004,

  // Provided by XR_META_virtual_keyboard
  XR_TYPE_VIRTUAL_KEYBOARD_MODEL_VISIBILITY_SET_INFO_META = 1000219005,

  // Provided by XR_META_virtual_keyboard
  XR_TYPE_VIRTUAL_KEYBOARD_ANIMATION_STATE_META = 1000219006,

  // Provided by XR_META_virtual_keyboard
  XR_TYPE_VIRTUAL_KEYBOARD_MODEL_ANIMATION_STATES_META = 1000219007,

  // Provided by XR_META_virtual_keyboard
  XR_TYPE_VIRTUAL_KEYBOARD_TEXTURE_DATA_META = 1000219009,

  // Provided by XR_META_virtual_keyboard
  XR_TYPE_VIRTUAL_KEYBOARD_INPUT_INFO_META = 1000219010,

  // Provided by XR_META_virtual_keyboard
  XR_TYPE_VIRTUAL_KEYBOARD_TEXT_CONTEXT_CHANGE_INFO_META = 1000219011,

  // Provided by XR_META_virtual_keyboard
  XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_COMMIT_TEXT_META = 1000219014,

  // Provided by XR_META_virtual_keyboard
  XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_BACKSPACE_META = 1000219015,

  // Provided by XR_META_virtual_keyboard
  XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_ENTER_META = 1000219016,

  // Provided by XR_META_virtual_keyboard
  XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_SHOWN_META = 1000219017,

  // Provided by XR_META_virtual_keyboard
  XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_HIDDEN_META = 1000219018,

  // Provided by XR_OCULUS_external_camera
  XR_TYPE_EXTERNAL_CAMERA_OCULUS = 1000226000,

  // Provided by XR_META_vulkan_swapchain_create_info
  XR_TYPE_VULKAN_SWAPCHAIN_CREATE_INFO_META = 1000227000,

  // Provided by XR_META_performance_metrics
  XR_TYPE_PERFORMANCE_METRICS_STATE_META = 1000232001,

  // Provided by XR_META_performance_metrics
  XR_TYPE_PERFORMANCE_METRICS_COUNTER_META = 1000232002,

  // Provided by XR_FB_spatial_entity_storage_batch
  XR_TYPE_SPACE_LIST_SAVE_INFO_FB = 1000238000,

  // Provided by XR_FB_spatial_entity_storage_batch
  XR_TYPE_EVENT_DATA_SPACE_LIST_SAVE_COMPLETE_FB = 1000238001,

  // Provided by XR_FB_spatial_entity_user
  XR_TYPE_SPACE_USER_CREATE_INFO_FB = 1000241001,

  // Provided by XR_META_headset_id
  XR_TYPE_SYSTEM_HEADSET_ID_PROPERTIES_META = 1000245000,

  // Provided by XR_META_recommended_layer_resolution
  XR_TYPE_RECOMMENDED_LAYER_RESOLUTION_META = 1000254000,

  // Provided by XR_META_recommended_layer_resolution
  XR_TYPE_RECOMMENDED_LAYER_RESOLUTION_GET_INFO_META = 1000254001,

  // Provided by XR_META_passthrough_color_lut
  XR_TYPE_SYSTEM_PASSTHROUGH_COLOR_LUT_PROPERTIES_META = 1000266000,

  // Provided by XR_META_passthrough_color_lut
  XR_TYPE_PASSTHROUGH_COLOR_LUT_CREATE_INFO_META = 1000266001,

  // Provided by XR_META_passthrough_color_lut
  XR_TYPE_PASSTHROUGH_COLOR_LUT_UPDATE_INFO_META = 1000266002,

  // Provided by XR_META_passthrough_color_lut
  XR_TYPE_PASSTHROUGH_COLOR_MAP_LUT_META = 1000266100,

  // Provided by XR_META_passthrough_color_lut
  XR_TYPE_PASSTHROUGH_COLOR_MAP_INTERPOLATED_LUT_META = 1000266101,

  // Provided by XR_META_spatial_entity_mesh
  XR_TYPE_SPACE_TRIANGLE_MESH_GET_INFO_META = 1000269001,

  // Provided by XR_META_spatial_entity_mesh
  XR_TYPE_SPACE_TRIANGLE_MESH_META = 1000269002,

  // Provided by XR_FB_face_tracking2
  XR_TYPE_SYSTEM_FACE_TRACKING_PROPERTIES2_FB = 1000287013,

  // Provided by XR_FB_face_tracking2
  XR_TYPE_FACE_TRACKER_CREATE_INFO2_FB = 1000287014,

  // Provided by XR_FB_face_tracking2
  XR_TYPE_FACE_EXPRESSION_INFO2_FB = 1000287015,

  // Provided by XR_FB_face_tracking2
  XR_TYPE_FACE_EXPRESSION_WEIGHTS2_FB = 1000287016,

  // Provided by XR_HTC_passthrough
  XR_TYPE_PASSTHROUGH_CREATE_INFO_HTC = 1000317001,

  // Provided by XR_HTC_passthrough
  XR_TYPE_PASSTHROUGH_COLOR_HTC = 1000317002,

  // Provided by XR_HTC_passthrough
  XR_TYPE_PASSTHROUGH_MESH_TRANSFORM_INFO_HTC = 1000317003,

  // Provided by XR_HTC_passthrough
  XR_TYPE_COMPOSITION_LAYER_PASSTHROUGH_HTC = 1000317004,

  // Provided by XR_HTC_foveation
  XR_TYPE_FOVEATION_APPLY_INFO_HTC = 1000318000,

  // Provided by XR_HTC_foveation
  XR_TYPE_FOVEATION_DYNAMIC_MODE_INFO_HTC = 1000318001,

  // Provided by XR_HTC_foveation
  XR_TYPE_FOVEATION_CUSTOM_MODE_INFO_HTC = 1000318002,

  // Provided by XR_HTC_anchor
  XR_TYPE_SYSTEM_ANCHOR_PROPERTIES_HTC = 1000319000,

  // Provided by XR_HTC_anchor
  XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_HTC = 1000319001,

  // Provided by XR_EXT_active_action_set_priority
  XR_TYPE_ACTIVE_ACTION_SET_PRIORITIES_EXT = 1000373000,

  // Provided by XR_MNDX_force_feedback_curl
  XR_TYPE_SYSTEM_FORCE_FEEDBACK_CURL_PROPERTIES_MNDX = 1000375000,

  // Provided by XR_MNDX_force_feedback_curl
  XR_TYPE_FORCE_FEEDBACK_CURL_APPLY_LOCATIONS_MNDX = 1000375001,

  // Provided by XR_EXT_hand_tracking_data_source
  XR_TYPE_HAND_TRACKING_DATA_SOURCE_INFO_EXT = 1000428000,

  // Provided by XR_EXT_hand_tracking_data_source
  XR_TYPE_HAND_TRACKING_DATA_SOURCE_STATE_EXT = 1000428001,

  // Provided by XR_EXT_plane_detection
  XR_TYPE_PLANE_DETECTOR_CREATE_INFO_EXT = 1000429001,

  // Provided by XR_EXT_plane_detection
  XR_TYPE_PLANE_DETECTOR_BEGIN_INFO_EXT = 1000429002,

  // Provided by XR_EXT_plane_detection
  XR_TYPE_PLANE_DETECTOR_GET_INFO_EXT = 1000429003,

  // Provided by XR_EXT_plane_detection
  XR_TYPE_PLANE_DETECTOR_LOCATIONS_EXT = 1000429004,

  // Provided by XR_EXT_plane_detection
  XR_TYPE_PLANE_DETECTOR_LOCATION_EXT = 1000429005,

  // Provided by XR_EXT_plane_detection
  XR_TYPE_PLANE_DETECTOR_POLYGON_BUFFER_EXT = 1000429006,

  // Provided by XR_EXT_plane_detection
  XR_TYPE_SYSTEM_PLANE_DETECTION_PROPERTIES_EXT = 1000429007,

  // Provided by XR_EXT_user_presence
  XR_TYPE_EVENT_DATA_USER_PRESENCE_CHANGED_EXT = 1000470000,

  // Provided by XR_EXT_user_presence
  XR_TYPE_SYSTEM_USER_PRESENCE_PROPERTIES_EXT = 1000470001,

  // Provided by XR_KHR_vulkan_enable2
  XR_TYPE_GRAPHICS_BINDING_VULKAN2_KHR = XR_TYPE_GRAPHICS_BINDING_VULKAN_KHR,

  // Provided by XR_KHR_vulkan_enable2
  XR_TYPE_SWAPCHAIN_IMAGE_VULKAN2_KHR = XR_TYPE_SWAPCHAIN_IMAGE_VULKAN_KHR,

  // Provided by XR_KHR_vulkan_enable2
  XR_TYPE_GRAPHICS_REQUIREMENTS_VULKAN2_KHR = XR_TYPE_GRAPHICS_REQUIREMENTS_VULKAN_KHR,

  // Provided by XR_FB_haptic_pcm
  XR_TYPE_DEVICE_PCM_SAMPLE_RATE_GET_INFO_FB = XR_TYPE_DEVICE_PCM_SAMPLE_RATE_STATE_FB,
  XR_STRUCTURE_TYPE_MAX_ENUM = 0x7FFFFFFF
}

[StructLayout(LayoutKind.Sequential)]
public struct XrInstanceCreateInfo
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrInstanceCreateFlags CreateFlags;
  public XrApplicationInfo ApplicationInfo;

  public uint EnabledApiLayerCount;
  public IntPtr EnabledApiLayerNames;
  public uint EnabledExtensionCount;
  public IntPtr EnabledExtensionNames;

  public void EnableExtensions(string[] ext)
  {
    EnabledExtensionNames = MarshalStringArray(ext);
    EnabledExtensionCount = (uint)ext.Length;
  }

  // Метод для преобразования массива строк в IntPtr
  private static IntPtr MarshalStringArray(string[] strings)
  {
    var ptr = IntPtr.Zero;
    if (strings is { Length: > 0 })
    {
      var size = IntPtr.Size;
      ptr = Marshal.AllocHGlobal(strings.Length * size);
      for (var i = 0; i < strings.Length; i++)
        Marshal.WriteIntPtr(ptr, i * size, Marshal.StringToHGlobalAnsi(strings[i]));
    }

    return ptr;
  }
}

[StructLayout(LayoutKind.Sequential)]
public struct XrApiLayerProperties
{
  public XrStructureType Type;
  public IntPtr Next;

  [MarshalAs(UnmanagedType.ByValTStr, SizeConst = (int)OpenXR.XR_MAX_API_LAYER_NAME_SIZE)]
  public string LayerName;

  public XrVersion SpecVersion;
  public uint LayerVersion;

  [MarshalAs(UnmanagedType.ByValTStr, SizeConst = (int)OpenXR.XR_MAX_API_LAYER_DESCRIPTION_SIZE)]
  public string Description;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrInstanceProperties
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrVersion RuntimeVersion;

  [MarshalAs(UnmanagedType.ByValTStr, SizeConst = (int)OpenXR.XR_MAX_RUNTIME_NAME_SIZE)]
  public string RuntimeName;

  public void PrintVersion()
  {
    Console.WriteLine(
      $"{RuntimeName} - {OpenXR.XR_VERSION_MAJOR(RuntimeVersion)}.{OpenXR.XR_VERSION_MINOR(RuntimeVersion)}.{OpenXR.XR_VERSION_PATCH(RuntimeVersion)}");
  }
};

[StructLayout(LayoutKind.Sequential)]
public struct XrSystemGetInfo
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrFormFactor FormFactor;
};

[StructLayout(LayoutKind.Sequential)]
public struct XrSystemProperties
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrSystemId SystemId;
  public uint VendorId;

  [MarshalAs(UnmanagedType.ByValTStr, SizeConst = (int)OpenXR.XR_MAX_SYSTEM_NAME_SIZE)]
  public string SystemName;

  public XrSystemGraphicsProperties GraphicsProperties;
  public XrSystemTrackingProperties TrackingProperties;
};

[StructLayout(LayoutKind.Sequential)]
public struct XrSystemGraphicsProperties
{
  public uint MaxSwapchainImageHeight;
  public uint MaxSwapchainImageWidth;
  public uint MaxLayerCount;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrSystemTrackingProperties
{
  public XrBool32 OrientationTracking;
  public XrBool32 PositionTracking;
};

[StructLayout(LayoutKind.Sequential)]
public struct XrSessionCreateInfo
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrSessionCreateFlags CreateFlags;
  public XrSystemId SystemId;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrGraphicsBindingOpenGLWin32KHR
{
  public XrStructureType Type;
  public IntPtr Next;
  public IntPtr hDC;
  public IntPtr hGLRC;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrGraphicsRequirementsOpenGLKHR
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrVersion MinApiVersionSupported;
  public XrVersion MaxApiVersionSupported;

  public void PrintVersion()
  {
    var min =
      $"{OpenXR.XR_VERSION_MAJOR(MinApiVersionSupported)}.{OpenXR.XR_VERSION_MINOR(MinApiVersionSupported)}.{OpenXR.XR_VERSION_PATCH(MinApiVersionSupported)}";
    var max =
      $"{OpenXR.XR_VERSION_MAJOR(MaxApiVersionSupported)}.{OpenXR.XR_VERSION_MINOR(MaxApiVersionSupported)}.{OpenXR.XR_VERSION_PATCH(MaxApiVersionSupported)}";
    Console.WriteLine($"Min API - {min}. Max API - {max}");
  }
}

public enum XrSessionState
{
  XR_SESSION_STATE_UNKNOWN = 0,
  XR_SESSION_STATE_IDLE = 1,
  XR_SESSION_STATE_READY = 2,
  XR_SESSION_STATE_SYNCHRONIZED = 3,
  XR_SESSION_STATE_VISIBLE = 4,
  XR_SESSION_STATE_FOCUSED = 5,
  XR_SESSION_STATE_STOPPING = 6,
  XR_SESSION_STATE_LOSS_PENDING = 7,
  XR_SESSION_STATE_EXITING = 8,
  XR_SESSION_STATE_MAX_ENUM = 0x7FFFFFFF
}

[StructLayout(LayoutKind.Sequential)]
public struct XrEventDataBuffer
{
  public XrStructureType Type;
  public IntPtr Next;

  [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4000)]
  public byte[] Varying;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrEventDataSessionStateChanged
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrSession Session;
  public XrSessionState State;
  public XrTime Time;
}

public enum XrViewConfigurationType
{
  XR_VIEW_CONFIGURATION_TYPE_PRIMARY_MONO = 1,
  XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO = 2,

  // Provided by XR_VARJO_quad_views
  XR_VIEW_CONFIGURATION_TYPE_PRIMARY_QUAD_VARJO = 1000037000,

  // Provided by XR_MSFT_first_person_observer
  XR_VIEW_CONFIGURATION_TYPE_SECONDARY_MONO_FIRST_PERSON_OBSERVER_MSFT = 1000054000,
  XR_VIEW_CONFIGURATION_TYPE_MAX_ENUM = 0x7FFFFFFF
}

[StructLayout(LayoutKind.Sequential)]
public struct XrSessionBeginInfo
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrViewConfigurationType PrimaryViewConfigurationType;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrSwapchainCreateInfo
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrSwapchainCreateFlags CreateFlags;
  public XrSwapchainUsageFlags UsageFlags;
  public Int64 Format;
  public uint SampleCount;
  public uint Width;
  public uint Height;
  public uint FaceCount;
  public uint ArraySize;
  public uint MipCount;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrViewConfigurationView
{
  public XrStructureType Type;
  public IntPtr Next;
  public uint RecommendedImageRectWidth;
  public uint MaxImageRectWidth;
  public uint RecommendedImageRectHeight;
  public uint MaxImageRectHeight;
  public uint RecommendedSwapchainSampleCount;
  public uint MaxSwapchainSampleCount;

  public void PrintInfo()
  {
    var rw = RecommendedImageRectWidth;
    var rh = RecommendedImageRectHeight;
    var mw = MaxImageRectWidth;
    var mh = MaxImageRectHeight;
    Console.WriteLine(
      $"Recommended Res {rw}x{rh}. Max Res {mw}x{mh}. Sample count {RecommendedSwapchainSampleCount}/{MaxSwapchainSampleCount}");
  }
}

[Flags]
public enum XrSwapchainUsageFlags : ulong
{
  XR_SWAPCHAIN_USAGE_COLOR_ATTACHMENT_BIT = 0x00000001,
  XR_SWAPCHAIN_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT = 0x00000002,
  XR_SWAPCHAIN_USAGE_UNORDERED_ACCESS_BIT = 0x00000004,
  XR_SWAPCHAIN_USAGE_TRANSFER_SRC_BIT = 0x00000008,
  XR_SWAPCHAIN_USAGE_TRANSFER_DST_BIT = 0x00000010,
  XR_SWAPCHAIN_USAGE_SAMPLED_BIT = 0x00000020,
  XR_SWAPCHAIN_USAGE_MUTABLE_FORMAT_BIT = 0x00000040,
  XR_SWAPCHAIN_USAGE_INPUT_ATTACHMENT_BIT_MND = 0x00000080,
  XR_SWAPCHAIN_USAGE_INPUT_ATTACHMENT_BIT_KHR = 0x00000080
}

[Flags]
public enum XrSwapchainFormatGL : ulong
{
  GL_RGBA8 = 0x8058,
  GL_DEPTH_COMPONENT16 = 0x81a5,
  GL_RGB16F = 0x881b,
  GL_DEPTH24_STENCIL8 = 0x88f0,
  GL_R11F_G11F_B10F = 0x8c3a,
  GL_SRGB8_ALPHA8 = 0x8c43,
  GL_DEPTH_COMPONENT32F = 0x8cac,
  GL_DEPTH32F_STENCIL8 = 0x8cad,

  GL_RGBA16 = 0x805b,
  GL_RGBA16F = 0x881a,
  GL_SRGB8 = 0x8c41,
  GL_DEPTH_COMPONENT24 = 0x81a6
}

[StructLayout(LayoutKind.Sequential)]
public struct XrSwapchainImageBaseHeader
{
  public XrStructureType Type;
  public IntPtr Next;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrSwapchainImageOpenGLKHR
{
  public XrStructureType Type;
  public IntPtr Next;
  public uint Image;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrFrameState
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrTime PredictedDisplayTime;
  public XrDuration PredictedDisplayPeriod;
  public XrBool32 ShouldRender;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrFrameBeginInfo
{
  public XrStructureType Type;
  public IntPtr Next;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrFrameEndInfo
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrTime DisplayTime;
  public XrEnvironmentBlendMode EnvironmentBlendMode;

  public uint LayerCount;

  //public XrCompositionLayerBaseHeader[] Layers;
  public IntPtr Layers;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrCompositionLayerBaseHeader
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrCompositionLayerFlags LayerFlags;
  public XrSpace Space;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrFrameWaitInfo
{
  public XrStructureType Type;
  public IntPtr Next;
}

public enum XrEnvironmentBlendMode
{
  XR_ENVIRONMENT_BLEND_MODE_OPAQUE = 1,
  XR_ENVIRONMENT_BLEND_MODE_ADDITIVE = 2,
  XR_ENVIRONMENT_BLEND_MODE_ALPHA_BLEND = 3,
  XR_ENVIRONMENT_BLEND_MODE_MAX_ENUM = 0x7FFFFFFF
}

[Flags]
public enum XrCompositionLayerFlags : ulong
{
  XR_COMPOSITION_LAYER_CORRECT_CHROMATIC_ABERRATION_BIT = 0x00000001,
  XR_COMPOSITION_LAYER_BLEND_TEXTURE_SOURCE_ALPHA_BIT = 0x00000002,
  sXR_COMPOSITION_LAYER_UNPREMULTIPLIED_ALPHA_BIT = 0x00000004
}

[StructLayout(LayoutKind.Sequential)]
public struct XrCompositionLayerProjection
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrCompositionLayerFlags LayerFlags;
  public XrSpace Space;
  public uint ViewCount;
  public IntPtr Views;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrCompositionLayerProjectionView
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrPosef Pose;
  public XrFovf Fov;
  public XrSwapchainSubImage SubImage;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrPosef
{
  public XrQuaternionf Orientation;
  public XrVector3f Position;

  public override string ToString()
  {
    return $"Position: {Position}. Orientation: {Orientation}";
  }
}

[StructLayout(LayoutKind.Sequential)]
public struct XrVector3f
{
  public float X;
  public float Y;
  public float Z;

  public override string ToString()
  {
    return $"Vector3f({X}, {Y}, {Z})";
  }
}

[StructLayout(LayoutKind.Sequential)]
public struct XrQuaternionf
{
  public float X;
  public float Y;
  public float Z;
  public float W;

  public override string ToString()
  {
    return $"Quaternionf({X}, {Y}, {Z}, {W})";
  }
}

[StructLayout(LayoutKind.Sequential)]
public struct XrFovf
{
  public float AngleLeft;
  public float AngleRight;
  public float AngleUp;
  public float AngleDown;

  public override string ToString()
  {
    return $"L {AngleLeft} R {AngleRight} U {AngleUp} D {AngleDown}";
  }
}

[StructLayout(LayoutKind.Sequential)]
public struct XrSwapchainSubImage
{
  public XrSwapchain Swapchain;
  public XrRect2Di ImageRect;
  public uint ImageArrayIndex;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrRect2Di
{
  public XrOffset2Di Offset;
  public XrExtent2Di Extent;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrOffset2Di
{
  public int X;
  public int Y;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrExtent2Di
{
  public int Width;
  public int Height;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrReferenceSpaceCreateInfo
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrReferenceSpaceType ReferenceSpaceType;
  public XrPosef PoseInReferenceSpace;
}

public enum XrActionType
{
  XR_ACTION_TYPE_POSE_INPUT = 4
}

[StructLayout(LayoutKind.Sequential)]
public struct XrActionSpaceCreateInfo
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrAction Action;
  public XrPath SubactionPath;
  public XrPosef PoseInActionSpace;
};

[StructLayout(LayoutKind.Sequential)]
public struct XrActionSetCreateInfo
{
  public XrStructureType Type;
  public IntPtr Next;

  [MarshalAs(UnmanagedType.ByValTStr, SizeConst = OpenXR.XR_MAX_ACTION_SET_NAME_SIZE)]
  public string ActionSetName;

  [MarshalAs(UnmanagedType.ByValTStr, SizeConst = OpenXR.XR_MAX_LOCALIZED_ACTION_SET_NAME_SIZE)]
  public string LocalizedActionSetName;

  public uint Priority;

  /*public void SetActionName(string name)
  {
    ActionSetName = new char[OpenXR.XR_MAX_ACTION_NAME_SIZE];
    var count = Math.Min(name.Length, OpenXR.XR_MAX_ACTION_NAME_SIZE - 1);
    name.CopyTo(0, ActionSetName, 0, count);
    ActionSetName[count] = '\0';
  }

  public void SetLocalizedActionName(string name)
  {
    LocalizedActionSetName = new char[OpenXR.XR_MAX_ACTION_NAME_SIZE];
    var count = Math.Min(name.Length, OpenXR.XR_MAX_LOCALIZED_ACTION_NAME_SIZE - 1);
    name.CopyTo(0, LocalizedActionSetName, 0, count);
    LocalizedActionSetName[count] = '\0';
  }*/
};

[StructLayout(LayoutKind.Sequential)]
public struct XrActionCreateInfo
{
  public XrStructureType Type;
  public IntPtr Next;

  [MarshalAs(UnmanagedType.ByValTStr, SizeConst = OpenXR.XR_MAX_ACTION_NAME_SIZE)]
  public string ActionName;

  public XrActionType ActionType;
  public uint CountSubactionPaths;
  public IntPtr SubactionPaths;

  [MarshalAs(UnmanagedType.ByValTStr, SizeConst = OpenXR.XR_MAX_LOCALIZED_ACTION_NAME_SIZE)]
  public string LocalizedActionName;

  /*public void SetActionName(string name)
  {
    ActionName = new char[OpenXR.XR_MAX_ACTION_NAME_SIZE];
    var count = Math.Min(name.Length, OpenXR.XR_MAX_ACTION_NAME_SIZE - 1);
    name.CopyTo(0, ActionName, 0, count);
    ActionName[count] = '\0';
  }

  public void SetLocalizedActionName(string name)
  {
    LocalizedActionName = new char[OpenXR.XR_MAX_ACTION_NAME_SIZE];
    var count = Math.Min(name.Length, OpenXR.XR_MAX_LOCALIZED_ACTION_NAME_SIZE - 1);
    name.CopyTo(0, LocalizedActionName, 0, count);
    LocalizedActionName[count] = '\0';
  }*/
}

public enum XrReferenceSpaceType
{
  XR_REFERENCE_SPACE_TYPE_VIEW = 1,
  XR_REFERENCE_SPACE_TYPE_LOCAL = 2,
  XR_REFERENCE_SPACE_TYPE_STAGE = 3,

  // Provided by XR_MSFT_unbounded_reference_space
  XR_REFERENCE_SPACE_TYPE_UNBOUNDED_MSFT = 1000038000,

  // Provided by XR_VARJO_foveated_rendering
  XR_REFERENCE_SPACE_TYPE_COMBINED_EYE_VARJO = 1000121000,

  // Provided by XR_ML_localization_map
  XR_REFERENCE_SPACE_TYPE_LOCALIZATION_MAP_ML = 1000139000,

  // Provided by XR_EXT_local_floor
  XR_REFERENCE_SPACE_TYPE_LOCAL_FLOOR_EXT = 1000426000,
  XR_REFERENCE_SPACE_TYPE_MAX_ENUM = 0x7FFFFFFF
}

[StructLayout(LayoutKind.Sequential)]
public struct XrExtensionProperties
{
  public XrStructureType Type;
  public IntPtr Next;

  [MarshalAs(UnmanagedType.ByValTStr, SizeConst = (int)OpenXR.XR_MAX_EXTENSION_NAME_SIZE)]
  public string ExtensionName;

  public uint ExtensionVersion;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrSwapchainImageAcquireInfo
{
  public XrStructureType Type;
  public IntPtr Next;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrSwapchainImageWaitInfo
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrDuration Timeout;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrSwapchainImageReleaseInfo
{
  public XrStructureType Type;
  public IntPtr Next;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrView
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrPosef Pose;
  public XrFovf Fov;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrViewState
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrViewStateFlags ViewStateFlags;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrViewLocateInfo
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrViewConfigurationType ViewConfigurationType;
  public XrTime DisplayTime;
  public XrSpace Space;
}

[StructLayout(LayoutKind.Sequential)]
public struct XrSpaceLocation
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrSpaceLocationFlags LocationFlags;
  public XrPosef Pose;
};

[StructLayout(LayoutKind.Sequential)]
public struct XrActionStateFloat
{
  public XrStructureType Type;
  public IntPtr Next;
  public float CurrentState;
  public XrBool32 ChangedSinceLastSync;
  public XrTime LastChangeTime;
  public XrBool32 IsActive;
};

[StructLayout(LayoutKind.Sequential)]
public struct XrActionStateBoolean
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrBool32 CurrentState;
  public XrBool32 ChangedSinceLastSync;
  public XrTime LastChangeTime;
  public XrBool32 IsActive;
};

[StructLayout(LayoutKind.Sequential)]
public struct XrActionsSyncInfo
{
  public XrStructureType Type;
  public IntPtr Next;
  public uint CountActiveActionSets;
  public IntPtr ActiveActionSets;
};

[StructLayout(LayoutKind.Sequential)]
public struct XrActiveActionSet
{
  public XrActionSet ActionSet;
  public XrPath SubactionPath;
};

[StructLayout(LayoutKind.Sequential)]
public struct XrActionStatePose
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrBool32 IsActive;
};

[StructLayout(LayoutKind.Sequential)]
public struct XrActionStateGetInfo
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrAction Action;
  public XrPath SubactionPath;
};

[StructLayout(LayoutKind.Sequential)]
public struct XrSessionActionSetsAttachInfo
{
  public XrStructureType Type;
  public IntPtr Next;
  public uint CountActionSets;
  public IntPtr ActionSets;
};

[StructLayout(LayoutKind.Sequential)]
public struct XrActionSuggestedBinding
{
  public XrAction Action;
  public XrPath Binding;
};

[StructLayout(LayoutKind.Sequential)]
public struct XrInteractionProfileSuggestedBinding
{
  public XrStructureType Type;
  public IntPtr Next;
  public XrPath InteractionProfile;
  public uint CountSuggestedBindings;
  public IntPtr SuggestedBindings;
};

public static partial class OpenXR
{
  public const uint XR_TRUE = 1;
  public const uint XR_FALSE = 0;
  public const uint XR_MAX_EXTENSION_NAME_SIZE = 128;
  public const uint XR_MAX_API_LAYER_NAME_SIZE = 256;
  public const uint XR_MAX_API_LAYER_DESCRIPTION_SIZE = 256;
  public const uint XR_MAX_SYSTEM_NAME_SIZE = 256;
  public const uint XR_MAX_APPLICATION_NAME_SIZE = 128;
  public const uint XR_MAX_ENGINE_NAME_SIZE = 128;
  public const uint XR_MAX_RUNTIME_NAME_SIZE = 128;
  public const uint XR_MAX_PATH_LENGTH = 256;
  public const uint XR_MAX_STRUCTURE_NAME_SIZE = 64;
  public const uint XR_MAX_RESULT_STRING_SIZE = 64;
  public const int XR_MAX_ACTION_SET_NAME_SIZE = 64;
  public const int XR_MAX_LOCALIZED_ACTION_SET_NAME_SIZE = 128;
  public const int XR_MAX_ACTION_NAME_SIZE = 64;
  public const int XR_MAX_LOCALIZED_ACTION_NAME_SIZE = 128;
  public const ulong XR_INFINITE_DURATION = 0x7fffffffffffffffL;

  // Флаги валидности положения и ориентации
  public const long XR_SPACE_LOCATION_POSITION_VALID_BIT = 1;
  public const long XR_SPACE_LOCATION_ORIENTATION_VALID_BIT = 2;

  public static XrVersion XR_MAKE_VERSION(ulong major, ulong minor, ulong patch)
  {
    return ((major & 0xffffUL) << 48) | ((minor & 0xffffUL) << 32) | (patch & 0xffffffffUL);
  }

  public static XrVersion XR_CURRENT_API_VERSION => XR_MAKE_VERSION(1, 0, 34);

  public static ushort XR_VERSION_MAJOR(ulong version)
  {
    return (ushort)((version >> 48) & 0xffff);
  }

  public static ushort XR_VERSION_MINOR(ulong version)
  {
    return (ushort)((version >> 32) & 0xffff);
  }

  public static uint XR_VERSION_PATCH(ulong version)
  {
    return (uint)(version & 0xffffffff);
  }

  public static XrResult xrGetOpenGLGraphicsRequirementsKHR(XrInstance instance, ulong systemId,
    ref XrGraphicsRequirementsOpenGLKHR graphicsRequirements)
  {
    var namePtr = Marshal.StringToHGlobalAnsi("xrGetOpenGLGraphicsRequirementsKHR");


    // Get procedure
    var fnPtr = IntPtr.Zero;
    var r = xrGetInstanceProcAddr(instance, namePtr, ref fnPtr);
    //Console.WriteLine("xrGetOpenGLGraphicsRequirementsKHR = " + r);

    var rr = Marshal.GetDelegateForFunctionPointer<xrGetOpenGLGraphicsRequirementsKHRDelegate>(fnPtr)(instance,
      systemId, ref graphicsRequirements);

    Marshal.FreeHGlobal(namePtr);
    return rr;
  }

  public delegate XrResult xrGetOpenGLGraphicsRequirementsKHRDelegate(XrInstance instance, ulong systemId,
    ref XrGraphicsRequirementsOpenGLKHR graphicsRequirements);

  // Return result
  public static (XrResult status, XrEventDataBuffer data) xrPollEvents(XrInstance xrInstance)
  {
    var eventData = new XrEventDataBuffer
    {
      Type = XrStructureType.XR_TYPE_EVENT_DATA_BUFFER
    };
    var status = xrPollEvent(xrInstance, ref eventData);
    return (status, eventData);
  }

  /*[DllImport("D:/csharp_lib/MegaLib/MegaLib/lib/openxr_loader.dll", CharSet = CharSet.Ansi,
    CallingConvention = CallingConvention.Cdecl, SetLastError = true)]
  public static extern XrResult xrLocateViews(XrSession session, ref XrViewLocateInfo viewLocateInfo,
    ref XrViewState viewState, uint viewCapacityInput, out uint viewCountOutput, [In, Out] XrView[] views);*/
}